### ISSUE TITLE
Work in any shell (bash, zsh, etc)

### ISSUE THREAD

**Issue by douglascamata** [turicas/sbc#10]
I think it'll work just chaging all /bin/bash references to /bin/sh. Or maybe parsing the user's login shell everytime something runs under the shell.

**Comment by turicas** [comment]
The `sbc` script (and all the others) currently can't run in `/bin/sh` -- it use some things related to bash.
We need to change it before changing all hashbangs. I think the most of the changes are related to subshells (replace `$(...)` with ``...``.

After replacing it we should only use shells that support `-l` (for login shell) and `-c` (for command execution) options and loading of `$HOME/.profile` on initialization (we are using it to add a new directory on `$PATH`).

**UPDATE**: maybe we don't need `-c`, only `-l` and `$HOME/.profile` (the shell that will execute `sbc-startup` can be any (`/bin/sh` for example)).

What are the most used shells?
- `bash` (100% compatible -- we use it!)
- `dash` (compatible with `-l`, `-c` and `$HOME/.profile`)
- `zsh` (compatible with `-c` and `$HOME/.profile` but not with `-l`)
- `ksh` (compatible with `$HOME/.profile` but not with `-l` and `-c`)
- `csh` (seems to be compatible)
- `tcsh` (seems to be compatible)
- `busybox` (?)

Am I missing any...?

Note: `sh` on Ubuntu it is linked to `dash`.

**Comment by turicas** [comment]
The shell being used on server should also support adding a directory to the path -- today we add a line overwriting var `$PATH` on `$HOME/.profile` (it works for bash but don't know if works for all other shells).

**Comment by douglascamata** [comment]
I think all the shells support that. I'm only sure that zsh support it.

**Comment by turicas** [comment]
`dash`, `bash`, `ksh` and `zsh` supports `$HOME/.profile` (for login shells). `csh` and `tcsh` don't support. I didn't found information about `busybox`. The only one that appears to support all we need is `dash`. Need to find a way to solve the problem about `-l` and `-c` on `ksh` and `-l` on `zsh`.

**Comment by douglascamata** [comment]
What does `-l` do on zsh that you need? And what command use it?

**Comment by turicas** [comment]
It starts a login shell. I think there is no problem passing `-l` to `zsh` command (it'll ignore it but will start a login shell apparently). Maybe the same occurs with `ksh`.

`ksh` uses `exec` option to execute commands, so the equivalence on `ksh` for bash's `bash -c "some command"` is `ksh exec "some command"`. But thinking more deeply, maybe we don't need `-c` option (only `-l`), since the script `sbc-startup` can run on any shell (it can be `/bin/sh`) -- I need to do some tests.

**Comment by kurtkraut** [comment]
This project will be useful for that matter: http://sourceforge.net/projects/checkbaskisms/

**Comment by douglascamata** [comment]
@turicas do you know is this supports [fish](http://fishshell.com/)? I'm currently using (and loving) it.

**Comment by turicas** [comment]
@douglascamata, `sbc` still needs bash to run, but now it will work even if you default local shell and your default remote shell are not bash. It just needs bash to interpret the commands, but you can call `sbc` from any shell (@kurtkurat and me tested on bash, dash and zsh). Can you please test the current develop branch?

Please see issue #20 if you want to track development related to do not depend on bash to execute sbc.

**Comment by kurtkraut** [comment]
@douglascamata We are turning sbc more shell agnostic. We are proof testing it to dash but in occasional tests with csh, ksh and zsh everything went fine. Give it a try on fish and give us a feedback.   If fish doesn't anything fancy, it is expected to work.

**Comment by kurtkraut** [comment]
@douglascamata I tested fish on both ends (local and remote) as a default shell and we found a bug. This was fixed in commit 2b65c5d3869bb6664a2786e69b64b11bb2be29af and now fish support is verified. Have a happy fishing!

**Comment by douglascamata** [comment]
@turicas @kurtkraut thank you, guys! :+1:
