### ISSUE TITLE
Setup breaks on second step

### ISSUE THREAD

**Issue by IngwiePhoenix** [turicas/sbc#26]
I am on OS X, and just tried to boss around my SSH a little with `sbc`...but sadly, it refuses to let me. :)

```
Ingwie@Ingwies-Macbook-Pro.local /V/S/D/turicas-sbc-d1ccec7  $ sbc setup root@ingwie.me
[sbc] Using existing key /Users/Ingwie/.ssh/sbc_rsa
[sbc] Copying private key to remote server...bash: sbc: command not found
```

`sbc` is installed in `/usr/local/bin/sbc`. The server I am connecting to already has passwordless authentification set io via priv/pubkey.

**Comment by turicas** [comment]
Hello, @IngwiePhoenix. Sorry for being late!

You must install `sbc` on the server first, before trying to `setup` it there. Just leave the `sbc` executable into one directories of `PATH` and try to run `sbc setup` again.

We need to create a better and easier way of installing/setting up.
