### ISSUE TITLE
Edit remote file from local environment

### ISSUE THREAD

**Issue by berinhard** [turicas/sbc#5]
Is there a way to evolve sbc adding a feature which makes possible for the user to edit remote file from his local machine? This [link](!http://vim.wikia.com/wiki/Editing_remote_files_via_scp_in_vim) could be a glue?

**Comment by flavioamieiro** [comment]
If you're not logged in the remote machine I think it makes more sense to just use your editor's built-in remote file support. That's what `sbc` uses anyways. 

For vim, as an example, this would be `vim scp://user@host//path/to/file`, as used in the [vim plugin implementation](https://github.com/turicas/sbc/blob/master/plugins/vim#L27).

UPDATE: Use two slashes for the filepath.
I don't see how `sbc` could help if you're not already with a shell on the remote machine. If you are, just using `sbc vim file` sould be enough.

Maybe I missunderstood your request, and maybe the link (that is broken) could help clarify things a little more.

**Comment by berinhard** [comment]
@flavioamieiro the link that is broken was just a reference to the snipet that you showed. I guess the snippet handles my question. Great job with the `sbc`.

**Comment by turicas** [comment]
Note that you need to use two slashes if you want to pass a absolute path, for example:

```
vim scp://user@host//home/user/test.txt
```

If you need to pass the path starting from user's home, use only one slash:

```
vim scp://user@host/test.txt
```

WRONG:

```
vim scp://user@host/home/user/test.txt
# it'll try to edit /home/user/home/user/test.txt
```
